### ISSUE TITLE
 confused about the process of Voxceleb2: Where does the input original 'raw' file come from?

### ISSUE THREAD

**Issue by someonefighting** [BUTSpeechFIT/EEND_dataprep#9]
Hello, I'm confused about the process of Voxceleb2. 
In my Voxceleb2, each speaker has multiple folders named by youtube id, and there are multiple m4a files under each youtube folder. 

eg. 
id00012:
├── f0Zj2NjXeyE
│   └── 00139.m4a
├── Gf-KDRnkBw8
│   ├── 00032.m4a
│   ├── 00033.m4a
│   ├── 00034.m4a

But in your "v2/VoxCeleb2/prepareKaldidata_VoxCeleb2.sh",  it seems like each youtube only has one raw file, eg. 

awk -v RAW_DIR=$RAW_DIR '{print $1" ffmpeg -f s16le -ar 16k -ac 1 -i "RAW_DIR"/"$1".**raw** -f wav pipe:1 |"}' $LIST > $DIR/Kaldidatadir/all/wav.scp

Where does the input original 'raw' file come from? Should I concatenate all m4a audio files in the same youtube folder into a raw file?

**Comment by fnlandini** [comment]
Hi,
Yes, what you say is correct. However, you do not need to have raw format. You can keep m4a and just update that line of the script accordingly. I used raw because we had the files like that but it is not necessary.
I hope this helps.

**Comment by someonefighting** [comment]
Thanks for your reply. When I concatenated the audios, I found another problem. 
Compared with your VAD segments, the length of the new concatenated ​​audio I got is shorter. Did you add silence intervals when splicing the original audio files?

**Comment by fnlandini** [comment]
Hi, yes you are right. A colleague of mine generated those concatenated versions and when doing so, he inserted 0.4s silence intervals in between each pair of segments. It is briefly commented in the [README](https://github.com/BUTSpeechFIT/EEND_dataprep/blob/main/v2/VoxCeleb2/VAD/README)

**Comment by someonefighting** [comment]
Thanks so much for clear explanation. 
Now i want to use a self-collected data to do the simulation, but the segments of each speaker are very short （3～6s）and discontinuous. If I treat these segments as if they are from the same long conversation, and concatenate them together in one utterance , is this okay？

**Comment by fnlandini** [comment]
Hard to say not knowing the details of the data. If for example the acoustic channel is very different across segments, when you put them together the system might pick up those differences rather than the speaker. So, in that case it's probably not a very good idea.
On the other hand, if the segments have similar characteristics (same microphone, similar background), maybe that will not be an issue.
I hope this helps.

**Comment by someonefighting** [comment]
In other words, do you think semantic continuity is important for conversation simulation?  The simulation data will be used to train a multi-talker ASR model later, using SOT if be more specifically. Although segments from a certain dataset can have similar characteristics, i'm not sure how important semantic continuity is in SOT training.  Do you have any experience to share about this?

**Comment by someonefighting** [comment]
Actually, I'm curious why TTS is not used for conversation simulation. Maybe I'm a little off topic，hhh

**Comment by someonefighting** [comment]
Thanks for your big help and i get the main point. I just realized that TTS is time and resource inefficient in online conversation simulation, and if I find anything I'll tell you again.
